### ISSUE TITLE
Add more project urls

### ISSUE THREAD

**Issue by jorgepiloto** [ansys/ansys-templates#132]
💡 **Add more project urls**
In the `pyrpoject.toml` file, the `[project.urls]` section looks like:

https://github.com/ansys/ansys-templates/blob/6dd76697c07fd51223ea7b2194ca42ff0b8483d9/pyproject.toml#L38-L39

However, the following links could be added too:

```toml
[project.urls]
Homepage = "https://github.com/ansys/ansys-templates/"
Documentation = "templates.pyansys.com/"
Source = "https://github.com/ansys-templates/ansys-templates"
Tracker = "https://github.com/ansys/ansys-templates/issues"

```
