### ISSUE TITLE
Add automatic GH actions update to ansys-templates

### ISSUE THREAD

**Issue by RobPasMue** [ansys/ansys-templates#136]
### 📝 Description of the feature

We have recently discovered that you can also automate the update of GH Actions with dependabot! 

### 💡 Steps for implementing the feature

Just placing the following piece of code in ``dependabot.yml``

```yaml
  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "daily"
```

### 🔗 Useful links and references

https://github.com/pyansys/pydisco/pull/152
