### ISSUE TITLE
Bug: `smoke-tests` should be named `build-wheelhouse` in the common `ci_cd.yml` template

### ISSUE THREAD

**Issue by anscfrisson** [ansys/ansys-templates#491]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

At [`src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/.github/workflows/ci_cd.yml`:](https://github.com/ansys/ansys-templates/blob/v3.0.0/src/ansys/templates/python/common/%7B%7Bcookiecutter.__project_name_slug%7D%7D/.github/workflows/ci_cd.yml#L52):

```
smoke-tests:
    name: "Build and Smoke tests"
    runs-on: {{ '${{ matrix.os }}' }}
    needs: [code-style]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        {% set required_minor = cookiecutter.__requires_python[2:] | int %}
        {%- set python_versions = [ ] -%}
        {%- for minor in range(9, 13) -%}
        {%- if minor >= required_minor -%}
        {{ python_versions.append("3." + minor | string ) or ''}}
        {%- endif -%}
        {%- endfor -%}
        python-version: {{ python_versions }}
    steps:
      - uses: ansys/actions/build-wheelhouse@v6
        with:
          library-name: {{ '${{ env.LIBRARY_NAME }}' }}
          operating-system: {{ '${{ matrix.os }}' }}
          python-version: {{ '${{ matrix.python-version }}' }}

  tests:
    name: "Tests"
    runs-on: {{ '${{ matrix.os }}' }}
    needs: [smoke-tests]
```

Job `smoke-tests` only performs action `build-wheelhouse`, so job should be renamed accordingly into `build-wheelhouse` to avoid confusion.

### 📝 Steps to reproduce

Create a new project with any template.

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
Does not matter.
```
